#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['webencodings']

package_data = \
{'': ['*']}

extras_require = \
{'doc': ['sphinx', 'furo'], 'test': ['pytest', 'ruff']}

setup(name='webencodings',
      version='0.6.1',
      description='Character encoding aliases for legacy web content',
      author=None,
      author_email='Simon Sapin <simon.sapin@exyr.org>',
      url=None,
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      python_requires='>=3.10',
     )
